version: "3"

services:
  app:
    restart: always
    build: .
    ports:
      - "6700:6700"

  redis:
    image: redis:alpine
    restart: always
    ports:
    -   6900:6379
    volumes:
    -   redis-data:/data

volumes:
  redis-data:
